### ISSUE TITLE
Two ports left open after ruinning tests

### ISSUE THREAD

**Issue by damoCl** [zack-bitcoin/amoveo#19]
Running tests on Ubuntu 17.10 , Intel Xeon platform.

Ports 3013 and 3030 were still open after running make tests. Had to be closed manually

Failed 2 tests. Output below 

```
======================================================================
FAIL: test_market (tests.test_market.MarketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/2TB/GIT/testing/amoveo/tests/test_market.py", line 28, in test_market
    self.request('new_channel_with_server', DEV_2_INT, [[127, 0, 0, 1], 3030, 27, 10000, 10001, 50, 4], sleep=0.04)
  File "/media/2TB/GIT/testing/amoveo/tests/base.py", line 90, in request
    return self._request(node, action, args, sleep)
  File "/media/2TB/GIT/testing/amoveo/tests/base.py", line 96, in _request
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200

======================================================================
FAIL: test (tests.test_share_blocks.ShareBlocksTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/2TB/GIT/testing/amoveo/tests/test_share_blocks.py", line 13, in test
    self.mine_block(DEV_2_INT, [1, 1], sleep=0.2)
  File "/media/2TB/GIT/testing/amoveo/tests/base.py", line 48, in mine_block
    return self._request(node, 'mine_block', args, sleep)
  File "/media/2TB/GIT/testing/amoveo/tests/base.py", line 96, in _request
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:3011 "POST / HTTP/1.1" 200 11
urllib3.connectionpool: DEBUG: http://localhost:3011 "POST / HTTP/1.1" 200 11
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:3021 "POST / HTTP/1.1" 500 0
--------------------- >> end captured logging << ---------------------
```

**Comment by zack-bitcoin** [comment]
Thank you for realing that the ports arent being closed.

I think this test is failing because it uses sleep instead of reacting to return values or callbacks.
Sleeps don't work on different computers because different computers need to sleep different amounts of time.

Either we need to fiX the commands to avoid sleeps, or we need to increase the amount of time it sleeps so that the test passes on more computers.

Or maybe test_market should only be run on servers that will actually be running a market. No reason to test unused code.

**Comment by damoCl** [comment]
Good
When i run  in production mode, and begin a sync, the program downloads 100 blocks first.
When I start mining another 56 blocks are created, for which the mining reward is added to the balance.

Is this the correct behavior of the program. I left it running over night, and when I came back to it, I had mined a few hundred blocks. However when I stop and clean the program, it restarted from block 156 again, and reset the balance.

Is the production mode acting as a stand alone node with the server, ( ie no interaction with other people testing the software.)

**Comment by damoCl** [comment]
Also, what procedure is used to  mine the blocks?

**Comment by zack-bitcoin** [comment]
To mine blocks:

mine:start()

You are right, only 100 blocks are being downloaded at a time. This is a problem.
Also it can't seem to share past 156 or so.

**Comment by zack-bitcoin** [comment]
The problem with sharing blocks is fixed in the newer version of the code.

I made some changes that may have fixed the problem that @damoCl found.
Do the tests still fail on @damoCl 's computer?

Would you mind sharing the log files if there are still errors?
/_build/dev1/rel/ae_core/log/crash.log
/_build/dev2/rel/ae_core/log/crash.log
/_build/dev3/rel/ae_core/log/crash.log

(remember to do `git pull` to download the new version of the code before running tests.)

**Comment by damoCl** [comment]
Sorry, Zach, I upgraded the ameveo code, and have overwritten  the crash logs. I'll back them up from now, in future.

Another issue I have found, is that if I modify your code to run on a few more cores, by modifying the block.erl file, at around line 367, Cores=10 for example, the miner will quickly mine 5 or 10 blocks, and then stop mining.

**Comment by zack-bitcoin** [comment]
Thank you for noticing this mining problem.

**Comment by zack-bitcoin** [comment]
I don't think mining from the core software is very important.
We need to set up software for GPU mining and mining pools as soon as possible.
Once GPU mining is possible, no one will mine with the core software anyway.

For now I will close this issue. feel free to open another.
