### ISSUE TITLE
mining starting nefore sync finished

### ISSUE THREAD

**Issue by damoCl** [zack-bitcoin/amoveo#31]
My machine appears  is mining before the sync has finished. 

I observed in the code that mine:start() calls sync:start(). however when I check my processors, they have appear to be mining. (ie, cores running at 100%). This should not happen until sync is finished, right??

Is there any way to check the correct blocks have been download from the console.

Blocks are stored, one per file. Do you have plans to store multiple blocks in one file. Its going to be a bit cumbersome at block 50,000 having 50,000 files stored in the blocks directory. 

Perhaps good to have a chainstate directory, in a leveldb database, before thing scale up.

**Comment by zack-bitcoin** [comment]
Yes, I believe the docs instruct you to sync first before mining. It would be cool if this happened automatically.

>is there any way to check if the correct block has been downloaded from the console?
If you have the most recent software, it should only download correct blocks.
You can look up block number 27 like this:
'blocks:get_by_height (27).'

Level dB would make things slower.
It's a hash table with page size P.
The stuff we store is size S.
If we needed to store N things in such a table, then it would be at least O (logP(S*N)) times slower than writing blocks to files.

Besides slowing us down, using leveldb would increase the surface area where bugs could be hiding.

When there are 50k blocks, you won't be able to do things like 'cat *', but the software should run correctly even if there are millions of blocks. 
Linux and Mac can hold many things in a single folder.

It would have been easier for me to use leveldB. I decided to take the more difficult route because I wanted a higher quality database than bitcoin or ethereum.

**Comment by damoCl** [comment]
I thought it does happen automatically, when you call mine:start(), from the call to ./apps/ae_core/src/consensus/mine.erl

start() ->
    sync:start(),
    gen_server:cast(?MODULE, start),
    timer:sleep(100),
    mine().

My question was  why the CPU is at 100% whilst this part of the code calls sync. Is this a particular feature of erl? If I call sync:start(), the CPU  is at 2%.

Having every block stored as a separate file creates a lot of overhead. Tcp/ip was never designed for transferring a lot of small files. It takes a lot longer to send 1000 small files over a tcp/ip connection than 1 file of them zipped.  Also on most operating systems files are stored in blocks. For a 4K block size there is no difference in storing 1 byte or 4K.  The smallest block is about 1.5K, so you have 2.5K of wasted storage. . 

Currently your testnet is at around block 2200. It's taking quite a while to sync them.

Wouldn't it be better to store blocks on top of each other in 1Mb files. It is a little more difficult, since you need an index to access particular blocks, but you avoid the problems mentioned.

I ran a little test. I created 50,000 files on ubuntu of size 20 bytes each, total 1 megabyte, with the command
```
/tmp/test> for i in {1..50000};do echo "file size, 20 bytes" > this_is_file_number_$i; done;
```
The size of all the files is 197 Mbytes.

I removed the files, rm * , no problem. When I created 100,000 files and tried to remove them
```
/tmp/test> for i in {1..100000};do echo "file size, 20 bytes" > this_is_file_number_$i; done;
/tmp/test> rm *
bash: /bin/rm: Argument list too long
```
Transferring the 100,000  files, from localhost to localhost on a tcp/ip connection took 35 seconds.

```
/tmp> scp -r  /tmp/temp ubuntu@localhost:/tmp/temp1
```

Tranfering a 1Mb file to local host over tcp/ip took  .016 seconds.

**Comment by damoCl** [comment]
You can remove the bugs in a (key, value) pair database, by xor'ing the key value, with an obfucated randomly generated value, which you also store in the database

**Comment by zack-bitcoin** [comment]
After calling sync, it allows sync to run in the background and immediately begins mining.
Right now there is no easy way to know when it is done syncing.
Mining significantly reduces the speed at which you can sync.
That is why the docs say to sync first, and then mine afterwards. 

Just because we are storing the blocks as independent files doesn't mean we have to transfer each block individually.
Right now we are transferring each block with a separate HTTP request. This was done to keep the code readable and simple for now. If this was updated to download multiple blocks in each HTTP request, it would be much faster, especially now when the blocks are empty.

You can still remove all the files in a folder this way `rm -r .`

Yes small files take up much more space than the data you store.
I want Amoveo to be able to support > megabyte blocks. When the block is a megabyte, you don't care about 0.001 megabytes of waste per block.

Yes, I know about the trick where you add salt to keys to stop people from making any individual branch of your database tree too long. It is a cool trick. I used it in an old version of the blockchain.
This is not why I avoid leveldb.
I avoid leveldb because leveldb would make the merkle tree about 3.5 times slower, and it would add a huge dependency to the project with possible security vulnerabilities. It would significantly increase the cost of maintaining Amoveo.

I don't think any other blockchain is using leveldb for storing blocks.
Bitcoin for example concatenates raw blocks, and stores them in a big file.

Many projects are using leveldb for writing their state trie on top of. Ethereum does this with their Merkle Patricia trie.

Leveldb keeps getting slower as the amount of data being stored gets bigger. The database I used instead of Leveldb doesn't slow down no matter how many things you store.
I once calculated that once Amoveo has millions of users, the Amoveo database would be about 3.5 times faster in comparison leveldb, but I can't find the data right now to double-check.
