### ISSUE TITLE
Error: mining_data from external source

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#60]
I was able to run the c-miner locally using 127.0.0.1:8081

I could not run the c-miner from another computer and point it at myserver:8080. I was able to hit other myserver:8080 endpoints such as pubkey and height, so the port was open fine.

I thought I might need to add a "doit" handler for mining_data in ext_handler.erl, but I didn't have luck doing that.

I'm not sure if the Light Node Wallet web page has the same or a different issue:
http://159.89.106.253:8080/wallet.html

I tried hitting the "mining_data" API on port 8080 and 8085 but no luck there.

![image](https://user-images.githubusercontent.com/35471470/35008492-469724c0-fac2-11e7-924f-187a506046cb.png)

**Comment by zack-bitcoin** [comment]
You can't connect a c-miner directly to a node on a different computer because port 8080 is restricted to programs running on the same computer. This part of the Api allows you to spend money, so it would be a security vulnerability to let untrusted people access it. 

There is mining pool software that uses port 8085 by default. It can be downloaded and installed seperately from Amoveo. 
The mining pool software allows you to connect many miners to a single full node that tells them what to work on.

https://github.com/zack-bitcoin/amoveo-mining-pool

**Comment by Mandelhoff** [comment]
That makes sense. I wasn't aware of the mining-pool project, and I got faked out by the supported local mining. I'll setup the pool and try again. Thank you.
