### ISSUE TITLE
Initial Account Details for new Full Node 

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#70]
I stood up a fresh full node, and it appears to have an account with a balance. I mined two blocks. It credited the account on my full node, so that worked for me.

![image](https://user-images.githubusercontent.com/35471470/35232032-02c64f12-ff60-11e7-839c-550e6ba751b7.png)

The pool appeared to pay out to the miner worker a 0.007 balance per block, which matches the code:

![image](https://user-images.githubusercontent.com/35471470/35231955-d316e380-ff5f-11e7-9f17-25ea06809c4f.png)

1) How do I set the account on the full node to something else? I tried several variations of keys:load but none had luck: With quotes, without quotes, base64 encoded, hex-ascii strings, etc...
keys:load("BOVs4Dnu43koQKf+6u3SIe0ghcHsYfMfYqxgO9Rf1y/locBazvrjqxtQMGAP8jr0Tas+43s1sOtYRDvvcZw6+fI=", "Base64encodedPrivateKeyValueHere", "password").
What should work?

2) Does the full node initialize to a new account or is it using a default existing account when a user first turns on the full node?

3) What is the format for the <<4, 104, 77...>>? It appears to be 0-255 byte values, but is it useful if the ... cuts off values in the keys?

4) On the api:account() print, is the first << >> the pub key? What is the second << >> set? (I suspect it's the private key, so I redacted it in red above.)

**Comment by Mandelhoff** [comment]
When I mined a block, the full node api:balance() increased by 138963. Is that the wallet balance in the full node or something else?

I'm confused that the node received 138963 and the miner wallet was paid 0.007, but maybe that's not apples-to-apples.

Thank you - I'll play around with the keys.db. Sounds like backing it up is a good idea. Would a restore just be copying the keys.db back up to a fresh node and squashing the default one?

**Comment by zack-bitcoin** [comment]
It is like bitcoin. There are 100 000 000 satoshis in one Veo.
So 0.007 Veo = 700 000 Satoshis.

The erlang node doesn't know anything about Veo, it only counts in Satoshis. 
The javascript light wallet converts to Veo so that it is easier to read.

The mining pool is keeping 1/6th of the reward.
This is important because if 2 people find a block at the same time, the mining pool ends up paying both of them.

to restore a keys.db file, first make sure that the node is turned off. Then replace the file. Then turn it on.

**Comment by Mandelhoff** [comment]
Sounds good: Pool paid 0.007 and wallet kept 0.00138963 per block.
Thank you.
