### ISSUE TITLE
Make Channel Failing on Light Wallet

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#86]
I have an account with 3.0 veo, and I tried to lock 2.0 veo in a channel with your 159.x server. I asked it to last 4700 blocks, and tried delay values of 0, 1, 10, and 100. All had similar errors:

![image](https://user-images.githubusercontent.com/35471470/35691254-951bb03e-073d-11e8-9ed2-4374c1b79448.png)

**Comment by Mandelhoff** [comment]
I had a similar "no root element found" error when I clicked the "make bet" button on a channel that already existed from a few days ago.

![image](https://user-images.githubusercontent.com/35471470/35691710-d54ef71e-073e-11e8-8438-249a471ca964.png)

**Comment by zack-bitcoin** [comment]
I think you can click on the red box that says "XML Parsing Error" in order to get a list of of function calls that resulted in the error.
I think a delay of < 100 would not work.

It looks like the server has 19 coins, so it should be able to afford to have a channel with you.

It looks like 4 people have open channels with the server now. Maybe you couldn't make a channel because that account already had an open channel with the server? If this is the case, then clicking the "trustfully download channel state" button should recover your old channel.

**Comment by Mandelhoff** [comment]
The "make channel" xml parsing error account did not have a channel with the server. That was a brand new account. When I clicked the "trustfully download channel state", it gave me an empty json file: {}

Yes, the "make bet" xml parsing error was with an account that had a channel with the server.

**Comment by zack-bitcoin** [comment]
http://159.89.106.253:8080/explorer.html
I was able to put a bet in this market using a light node.
I just made the channel, and it worked.

So hopefully updating the light node to the new version of the software fixed it.

**Comment by Mandelhoff** [comment]
Confirmed. Updated channel works.

Making bets worked too, but I had to refresh my page and load my channel. I had mined after locking my channel and updated headers, but could not get the bet to work until I did a page refresh.
