### ISSUE TITLE
Block Found Errors

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#90]
My full node and pool are synced with your node (currently at block 468). They stayed in sync all day fine. I kicked off some mining tonight. When I found blocks, the height did not increase and balance of my node and miner did not increase. It's like the found blocks failed to commit. No one else is mining. Your node shows block 468 throughout my tests.

The full node has been spitting out errors like this screenshot. This is the output from finding one block. It appears to try the spend many times when the pool submits the block, but it's not successful.

I'm pretty certain my keys are unlocked as I did a few spends from my node earlier today.

![image](https://user-images.githubusercontent.com/35471470/35762530-71ec0ade-085d-11e8-9056-b23a42b17bc5.png)

**Comment by Mandelhoff** [comment]
Is this currently happening on the http://159.89.106.253 node too? I've mined a few blocks against http://159.89.106.253 and the height is still sitting at 620.

This still happens on my node, but my height was staying in sync with your node so I didn't blow it away yet.

**Comment by zack-bitcoin** [comment]
It looks like it is failing to spend money because you have none.
It publishes the block first before spending money, so it should still be able to mine even if it can't spend money.
I tested out mining with a mining pool, a full node, and a c-miner, and it worked correctly on the first try. The block heigh increased, and the blocks correct shared to the server.

So as of now, I don't have enough information to reproduce the error you found.

Make sure you do a `git pull` in all 3 repositories, amoveo, the miner, and the mining pool.

**Comment by Mandelhoff** [comment]
The spend attempt was 0.0001 from an account with 2.39 veo to an account with 34.0 veo.

Doesn't seem like that should "fail to spend".

**Comment by Mandelhoff** [comment]
I see that block height is increasing again. I tried a 0.001 spend and that completed.
