### ISSUE TITLE
Initial node sync failing?

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#93]
I got a fresh clone about 10 minutes ago. I did the start:sync() and it sync'd for a while. It seems to stall out.

I can run api:height(). and it tells me 2254 which is the height that your Explorer web page shows, but I keep getting timeouts and getblock errors like the screenshot.

The pool also gives an error saying the node isn't sync'd.

![image](https://user-images.githubusercontent.com/35471470/35834868-3f268b3c-0a9d-11e8-9be9-ff30ebfe0b67.png)

![image](https://user-images.githubusercontent.com/35471470/35834940-916aa8e2-0a9d-11e8-8cf1-0924e0d757b8.png)

**Comment by zack-bitcoin** [comment]
what does `block:height().` return?
api:height only tells you how many headers you have downloaded. Headers are a lot quicker than blocks.

It seems like your node is trying to contact one of the other nodes, and it is failing. 

Is this your public node? 
Are you mining?

When mining, the nodes contact each other regularly, and it would make sense if the message would occasionally fail, since my node has a lot of traffic and the software isn't perfect.

**Comment by Mandelhoff** [comment]
Public node - yes.
Mining - no. (My pool wouldn't start.)

I gave it a make prod-clean and then build. It's syncing well now. 

![image](https://user-images.githubusercontent.com/35471470/35835310-9aa16368-0a9f-11e8-8658-8628237c84c9.png)

If you have any tips about preventing the sync timeouts, please let me know.

**Comment by zack-bitcoin** [comment]
When you go offline, my node deletes yours from the list of peers.
And when you go offline, you delete your own list of peers.

**Comment by zack-bitcoin** [comment]
fixed sync:stop().
If you want to turn a node off while it is syncing, it is probably safest to stop the syncing first before you do api:off().
CANCELFORWARD 1 DELETE 1 REPLY EDIT
