### ISSUE TITLE
too many files libc.so.6

### ISSUE THREAD

**Issue by zack-bitcoin** [zack-bitcoin/amoveo#97]
on some systems where you are running a miner and a full node on the same computer, it seems like there are tons of miners running at once instead of just a few. Gonzalo witnessed this, hopefully he can explain more.

**Comment by nextquick** [comment]
The problem was that `killall` command was missing in my system (*), so the `amoveo-c-miner` was failing to kill the tasks. Instead of 1 task per core, running at 100%, we had hundreds.

Switching `killall` for `pkill` on `miner.erl` fixed the problem.

To avoid this problem in the future would be recommended to install `killall` among with the other dependencies.

(*) Ubuntu Xenial (16.04 LTS) (GNU/Linux 4.4.114-mainline-rev1 x86_64 )

**Comment by zack-bitcoin** [comment]
Great. Thank you for the help.
